### ISSUE TITLE
Getting some error code while running it

### ISSUE THREAD

**Issue by Nidllah** [c3er/plex-dl#1]
Am i doing something wrong?

Here is my secrets.json:

```
{
    "plexAccount": {
        "user": "actualmail@gmail.com>",
        "password": "myactualpassword111"
    }
}
```

Here is my complete error message:
```
PS F:\Hämtade Filer\plex-dl-master\plex-dl-master> python plex.py
Traceback (most recent call last):
  File "F:\Hämtade Filer\plex-dl-master\plex-dl-master\plex.py", line 125, in <module>
    main()
  File "F:\Hämtade Filer\plex-dl-master\plex-dl-master\plex.py", line 89, in main
    connection = (myplex.MyPlexAccount(credentials["user"], credentials["password"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\filip\AppData\Local\Programs\Python\Python311\Lib\site-packages\plexapi\myplex.py", line 124, in __init__
    data, initpath = self._signin(username, password, code, remember, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\filip\AppData\Local\Programs\Python\Python311\Lib\site-packages\plexapi\myplex.py", line 137, in _signin
    data = self.query(self.SIGNIN, method=self._session.post, data=payload, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\filip\AppData\Local\Programs\Python\Python311\Lib\site-packages\plexapi\myplex.py", line 239, in query
    raise Unauthorized(message)
plexapi.exceptions.Unauthorized: (401) unauthorized; https://plex.tv/api/v2/users/signin <?xml version="1.0" encoding="UTF-8"?> <errors>   <error code="1001" message="User could not be authenticated" status="401"/> </errors>
```

**Comment by c3er** [comment]
Thanks for filing this issue!

Unfortunately, I doubt that I can help you with this problem. I didn't use this tool for years and I have currently even no usable Plex access.

I can only provide some suggestions:

- Did you *really* write your credential data correctly? E.g. I see an invalid character at the end of your user name. Could your real `secrets.json` also contain this character? I know from my own experience that something like this can be overlooked very easily!
- Did you put a proper server name the line `SERVER = "Some server"`)?
- Wild guess: is your Plex account secured via 2 factor authentication? If yes, you have to set some options in your account settings to allow the script to authenticate just via a user name / password combination, like a special "app password" that has to be generated before.

I let you know, if I have more suggestions or a better idea. Please let me know whether and how you could resolve your problem!

Since I don't work with this tool and I'm currently even not able to work with it, I very welcome pull requests, if changes or additions to the code are necessary!

Good luck!
